#!/usr/bin/perl

=head1 NAME

 Hapmap2Mapmaker
 Tool to change Hapmap format to Mapmaker input format

=cut

=head1 SYPNOSIS

 Hapmap2mapmaker [-h]  -i <hapmap_inputfile> -o <outputfile>
                       -a <donor_a> -b <donor_b> -t <data_type>
                       [-k <keys>] [-f <outformat>] 
                       [-p <chisqr_pvalue>] [-s <segregation>]
                       [-e <samples_to_exclude>] [-d <distance_snps>] [-B][-H]
                       
=head1 EXAMPLE

       Hapmap2Mapmaker -i Laupala_HC1_Filter1_SNP.set_1.hmp.txt 
                       -o Laupala_HC1_Filter1_SNP.AHB121_markers_p001.csv 
                       -f csv 
                       -a HC1_D_Laeuk 
                       -b HC1_S_Lacer 
                       -e Reference 
                       -s '(a,h,b)' 
                       -p 0.001


=head2 I<Flags:>

=over


=item -i

B<hapmap_inputfile>       hapmap input file (mandatory)

=item -o

B<outputfile>             output filename (mandatory)

=item -f

B<output_format>          outout format: mapmaker (default), csv or jointmap4

=item -a

B<donor_a>                donor a name(s) (separated by commas) (mandatory)

=item -b

B<donor_b>                donor b name(s) (separated by commas) (mandatory)

=item -t

B<data_type>              data type for mapmaker (ex. f2) (f2 by default)

=item -k

B<keys>                   keys to code SNPs (aa=1;bb=2;ab=3...) 

=item -s

B<filter_segregation>     filter by expected segregation (optional)

=item -p

B<chisqr_pvalue>          chi square p-value for segregation test (0.01 default)

=item -e

B<samples_to_exclude>     list of samples to exclude (sep. by comma)

=item -B

B<biallelic_filter>       filter out the non biallelic genotypes.

=item -H

B<homozygous_donor>       select only homozygous markers for donors

=item -d

B<distance_snps>          filter snps closer than this distance

=item -V

B<be_verbose>             be verbose and print the parsing status.

=item -h

B<help>                   print the help

=back

=cut

=head1 DESCRIPTION

 This script trasforms a hapmap file into a Mapmaker format

 Hapmap format is a tabular format file with the following columns:
  C1:   rs#
  C2:   alleles
  C3:   chrom
  C4:   pos
  C5:   strand
  C6:   assembly
  C7:   center
  C8:   protLSID
  C9:   assyLSID	
  C10:  panelLSID	
  C11:  QCcode	
  C12+: Genotypes

 Mapmaker format with two header lines:
  line1: "data type XXXX"
         where XXXX can be "f2 intercross", "f2 backcross", "f3 self", 
         "ri self" or "ri sib" (remember that Antmap do not use: "ri sib" 
         but it can use "dh").
  line2: XXX YYY ZZZ Additional_AAAA
         where XXX is the number of the progeny (C12+ hapmap excluding 
         progenitors and -e accessions).
         where YYY is the number of genetic loci
         where ZZZ number of quantitative traits
         where Additional_AAAA is aditional information such as the coding
         scheme (keys), for example: "symbols 1=A 2=B 3=H 0=-")

   The standard key is:
    KEY     DESCRIPTION
    a       homozygote or haploid as the first donor (A)
    b       homozygote or haploid as the second donor (B)
    h       heterozygote
    c       not genotype a (the b-allele is dominant)
    d       not genotype b (the a-allele is dominant)
    –       genotype unknown
    x       genotype is not A or B

   After these two lines, the raw input file contains one line per locus
   where it starts with "*" plus the locus name, space (tab...) and the 
   genotypes, for example "*L1 ABABBBHH" or "*L1 A B A B B B H H". Locus names
   are limited to alphanumeric characters + underscores "_" or periods "." and
   must start with an aplhanumeric character.

   Comments can be inserted as "#". 
         
  Example hapmap:
  C1     C2   C3    C4    C5  C6  C7  C8  C9  C10  C11  S1  S2  S3  S4  S5  S6
  MRK01  A/T  Chr5  1000  +   NA  NA  NA  NA  NA   NA   AA  TT  AA  AT  AT  AA
  MRK02  C/T  Chr5  2000  +   NA  NA  NA  NA  NA   NA   CC  TT  CT  TT  CC  CC
  MRK03  C/G  Chr5  3000  +   NA  NA  NA  NA  NA   NA   CC  GG  CG  CG  GG  CG

  Using Hapmap2Mapmaker -a S1 -b S2 -e S6 -k aa=1;bb=2;ab=3;ac=4;bc=5;cc=6;-=0
  will produce: 

  Example mapmaker:
  data type f2 intercross
  3 3 0 symbols 1=A 2=B 3=H 4=C 5=D 0=-
  *MRK01 1 3 3
  *MRK02 3 2 1
  *MRK03 3 3 1

  If no key is used:

  Example mapmaker:
  data type f2 intercross
  3 3 0
  *MRK01 A H H
  *MRK02 H B A
  *MRK03 H H A
  
  Note: cc will be ignored because it is not one of the f2 defined marker types

  If more than one progenitor is used (for example -a S1,S6 it will try to find
  a consensus, if do not it will ignore that marker printing a comment).
 
  Example mapmaker:
  data type f2 intercross
  3 3 0
  *MRK01 A H H
  *MRK02 H B A
  ## MRK03 has different genotypes for progenitor a (S1,S6) CC,CG

  Biallelic (-B) option filter the non-biallelic SNPs (recommended).

  Filter for expected segregations:
    KEY             RATIO
    (a,b)           1:1
    (a,h)           1:1
    (a,c)           1:3
    (h,b)           1:1
    (b,d)           1:3
    (a,h,b)         1:2:1
    (ac,ad,bc,bd)   1:1:1:1
    (ee,ef,eg,fg)   1:1:1:1

=cut

=head1 AUTHORS

  Aureliano Bombarely Gomez.
  (ab782@cornell.edu).

=cut

=head1 METHODS

 Hapmap2Mapmaker


=cut

use strict;
use warnings;
use autodie;

use Getopt::Std;
use List::Util 'shuffle';

## It will calculate the chi square
use Statistics::Distributions;


our ($opt_i, $opt_o, $opt_f, $opt_a, $opt_b, $opt_t, $opt_k, $opt_e, $opt_d, 
     $opt_s, $opt_p, $opt_B, $opt_H, $opt_V, $opt_h);
getopts("i:o:f:a:b:t:k:e:d:s:p:BHVh");
if (!$opt_i && !$opt_o && !$opt_f && !$opt_a && !$opt_b && !$opt_t && !$opt_k 
    && !$opt_e && !$opt_d && !$opt_s && !$opt_p && !$opt_B && !$opt_H 
    && !$opt_V && !$opt_h) {
    print "There are n\'t any tags. Print help\n\n";
    help();
}
if ($opt_h) {
    help();
}

my $date = `date`;
chomp($date);
print STDERR "\n\n############################################################";
print STDERR "\n## Hapmap2FastaLike Starts ($date)  ##\n";
print STDERR "############################################################\n\n";

print_header("0) Checking arguments");

##############################################################################
## CHECK ARGUMENTS
##############################################################################

## Get the arguments and check them

my $input = $opt_i || 
    die("INPUT ARG. ERROR: -i <hapmap_input> argument was not supplied.\n");

print STDERR "\tInput file: $input\n";

my $output = $opt_o ||
    die("INPUT ARG. ERROR: -o <outputfile> argument was not supplied.\n");

print STDERR "\tOutput file: $output\n";
    
my $a_donor_line = $opt_a ||
    die("INPUT ARG. ERROR: -a <donor_a> argument was not supplied.\n");

## Check output format -f

my %oformats = (
    'jointmap4' => 1,
    'mapmaker'  => 1,
    'csv'       => 1
    );

my $oformat = 'mapmaker';
if ($opt_f) {

    unless (exists $oformats{$opt_f}) {
    
	die("ERROR: -f $opt_f is not a valid formta\n");
    }
    else {
    
	$oformat = $opt_f;
    }
}

my %a_donors = (); 
foreach my $ad (split(/,/, $a_donor_line)) {

    $a_donors{$ad} = 1;
}
my $a_donor_c = scalar(keys %a_donors);

print STDERR "\tA Donors ($a_donor_c): $a_donor_line\n";

my $b_donor_line = $opt_b ||
    die("INPUT ARG. ERROR: -b <donor_b> argument was not supplied.\n");

my %b_donors = ();
foreach my $bd (split(/,/, $b_donor_line)) {

    $b_donors{$bd} = 1;
}
my $b_donor_c = scalar(keys %b_donors);

print STDERR "\tB Donors ($b_donor_c): $b_donor_line\n";

my %types = (
    "f2 intercross" => 1, 
    "f2 backcross"  => 1, 
    "f3 self"       => 1, 
    "ri self"       => 1,
    "ri sib"        => 1,
    "dh"            => 1,
);

my $mtype = "f2 intercross";
if ($opt_t) {

    if (exists $types{$opt_t}) {
    
	$mtype = $opt_t;
    }
    else {
    
	die("ERROR: -t $opt_t is not a valid parameter. Check -h for options.");
    }
}

print STDERR "\tPopulation type: $mtype\n";

my %excluded = ();
if ($opt_e) {

    my @excluded = split(/,/, $opt_e);
    foreach my $exc (@excluded) {
    
	$excluded{$exc} = 1;
    }
    print STDERR "\tExcluded individuals: $opt_e\n";
}
else {

     print STDERR "\tNo excluded individuals\n";
}

if ($opt_B) {

    print STDERR "\tBiallelic filter [enabled]\n";
}
else {

    print STDERR "\tBiallelic filter [disabled]\n";
}

if ($opt_d) {

    if ($opt_d !~ m/^\d+$/) {
    
	die("ERROR: -d <filter_distance> is not a numeric value.\n");
    }
    else {
    
	print STDERR "\tDistance filter [enabled] ($opt_d bp)\n";
    }
}

if ($opt_H) {

    print STDERR "\tHomozygous donor selection [enabled]\n";
}
else {

    print STDERR "\tHomozygous donor selection [disabled]\n";
}

## segregation values will be order alphabetically

my %segreg = (
    "(a,b)"         =>  "1:1",
    "(a,h)"         =>  "1:1",
    "(a,c)"         =>  "1:3",
    "(b,h)"         =>  "1:1",
    "(b,d)"         =>  "1:3",
    "(a,b,h)"       =>  "1:1:2",
    "(ac,ad,bc,bd)" =>  "1:1:1:1",
    "(ee,ef,eg,fg)" =>  "1:1:1:1"    
    );


my $chisq_pvalue = 0.01;

if ($opt_s) {

    if ($opt_s =~ m/\(a,h,b\)/) {
    
	print STDERR "\tNote: Segregation reordered from (a,h,b) to (a,b,h)\n";
	$opt_s = '(a,b,h)';
    }

    unless (exists $segreg{$opt_s}) {
    
	die("ERROR: segregation -s $opt_s is no valid.\n");
    }
    else {
    
	print STDERR "\tFilter by segregation [enabled]: $opt_s\n";

	if ($opt_p) {
	    $chisq_pvalue = $opt_p; 
	}
	print STDERR "\tChi Square p-value: $chisq_pvalue\n";
    }
}
else {

    print STDERR "\tFilter by segregation [disabled]\n";
}



###############################################################################
## PARSE THE HAPMAP
###############################################################################
## The data will be stored with this structure:
##
## $marker_loc{$chrom} = { $id => $pos };
## $marker_abh{$id} = { $sample => $genotype };
###############################################################################

print_header("1) Parsing Hapmap input file");

my ($mk_abh_href, $mk_loc_href) = parse_hapmap($input, \%a_donors, \%b_donors, 
					       \%excluded);

my %marks = %{$mk_abh_href};

my $nmrks = scalar(keys %marks);
print STDERR "\t$nmrks makers have been extracted from the hapmap file.\n";

## Order the markers by position and filter according -d

print_header("2) Order markers and filter by distance");

my %chr_markers = sort_markers($mk_loc_href, $opt_d);

## Get all the info

my @chrs = sort keys %chr_markers;
my @first_marks = sort @{$chr_markers{$chrs[0]}};
my %first_genotypes = %{$marks{$first_marks[0]}};
my @indiv = sort keys %first_genotypes;

my $indiv_n = scalar(@indiv);


###############################################################################
## PRODUCE THE OUTPUT
###############################################################################

print_header("3) Filtering no biallelic markers");

if ($opt_B) {

    foreach my $mrk_id (sort keys %marks) {
    
	my %gnt = %{$marks{$mrk_id}};
	
	## Biallelic genotypes exclude 'X' ('C' and 'D' are not used)

	my $x_genotype = 0;
	foreach my $ind (sort keys %gnt) {

	    my $ind_gnt = $gnt{$ind};
	    if ($ind_gnt =~ m/^X$/i) {
	    
		$x_genotype = 1;
	    }
	}

	if ($x_genotype == 1) {
	
	    delete($marks{$mrk_id});
	}
    }
}
else {
    
    print STDERR "\tBiallelic filtering disabled.\n\tSkipping Step 3\n";
}
my $nmrks_r = scalar(keys %marks);
my $removed = $nmrks - $nmrks_r;
print STDERR "\t$removed makers have been filtered (biallelic).\n";


print_header("4) Filtering by segregation");

my %segregation = ();
my %segregation_stats = ();
    
## It will classify markers according their segregation ratio
## It will use a Chi-square rati

my %selected_marks = ();

foreach my $chr (@chrs) {

    foreach my $mid (@{$chr_markers{$chr}}) {

	my %gnt_count = count_genotypes($marks{$mid});
	my @genotypes = keys(%gnt_count);
	my $genotypes_line = "(" . lc(join(",", sort(@genotypes))) . ")";
    
	if (exists $segreg{$genotypes_line}) {
	    
	    my $segregation = $segreg{$genotypes_line};
	    my @segr_value = split(/:/, $segregation);
	    my $total = 0;
	    foreach my $sg (@segr_value) {
	    
		$total += $sg;
	    }
	    my $df = scalar(@segr_value) - 1;
	
	    ## build a segregation hash
	    my $i = 0;
	    my $x2 = 0;
	
	    my @test = ();
	
	    foreach my $sg (sort @genotypes) {
	    
		my $obs = $gnt_count{$sg};
		my $exp = ($segr_value[$i]/$total) * $indiv_n;
		
		my $single_x2 = (($obs - $exp)*($obs - $exp))/$exp;
		$x2 += $single_x2;
		push @test, ($sg, $gnt_count{$sg});
		$i++;
	    }    	    

	    my $p_value = Statistics::Distributions::chisqrprob($df,$x2);
	    my $testline = join(",", @test);

	    if ($p_value > $chisq_pvalue) {
	    
		$segregation{$mid} = $genotypes_line;
		$segregation_stats{$genotypes_line}++;

		if ($opt_s eq $genotypes_line) {
		    
		    $selected_marks{$mid} = $marks{$mid};
		}
		
		# print STDERR "Hypothesis ACCEPTED ($p_value > $chisq_pvalue)";
		# print STDERR "($testline) (It is a mendelian pattern)\n";
	    }
	    else {
	    
		$segregation{$mid} = 'None';
		$segregation_stats{"None"}++;	

		# print STDERR "Hypothesis REJECTED ($p_value < $chisq_pvalue)";
		# print STDERR "($testline) (It is a random distribution)\n"; 
	    }
	}
    }
}

print STDERR "\n\tSegregations Stats (Chi Square with p-value=";
print STDERR "$chisq_pvalue):\n";
foreach my $sgr (sort keys %segregation_stats) {
    
    print STDERR "\t$sgr\t$segregation_stats{$sgr}\n";
}

if ($opt_s) {

    print STDERR "\n\n\tSegregation filter $opt_s segregation $segreg{$opt_s}\n";
    my $marks_n = scalar(keys %selected_marks);
    print STDERR "\t$marks_n markers have been selected ($opt_s)\n";
}
else {
    
    print STDERR "\tSegregation filtering disabled.\n\tSkipping Step 4\n";
}


print_header("5) Printing Output");

## Only remains to get information about the number of markers

my $marks_n = scalar(keys %selected_marks);

## First get the info to print the headers.

open my $ofh, '>', $opt_o;

if ($oformat eq 'mapmaker') {
    
    print $ofh "data type $mtype\n";
    
    print $ofh "$indiv_n $marks_n 0\n\n";

    foreach my $chr (@chrs) {

	foreach my $mrk (@{$chr_markers{$chr}}) {
    
	    if (exists $selected_marks{$mrk}) {

		my %genotps = %{$marks{$mrk}};
		my @genotypes = ();
		foreach my $ind (@indiv) {
	
		    push @genotypes, $genotps{$ind};
		}
		my $geno_line = join(" ", @genotypes);
		print $ofh "*$mrk $geno_line\n";
	    }
	}
    }
}
elsif ($oformat eq 'jointmap4') {

    ## jointmap has an specific format for the populations

    my %jm4_poptype = (
	"f2 intercross" => "F2", 
	"f2 backcross"  => "BC1", 
	#"f3 self"       => 1, 
	"ri self"       => "RI2",
	#"ri sib"        => 1,
	"dh"            => "DH1",
	);

    print $ofh "name = hapmap2maker_pop\n";
    print $ofh "popt = $jm4_poptype{$mtype}\n";
    print $ofh "nloc = $marks_n\n\n";
    print $ofh "nind = $indiv_n\n";

    ## Jointmap can not have marker names with more than 20 characters
    ## It will change that producing a equivalent list at the end of the 
    ## file as a comment. 
    ## ; M00001 BlaBla555501:4009

    my %new_marks = ();
    my $length_tag = length($marks_n);
    my $c = 0;

    foreach my $chr (@chrs) {

	foreach my $mrk (@{$chr_markers{$chr}}) {
    
	    if (exists $selected_marks{$mrk}) {

		$c++;

		my $new_name = "M" . sprintf("%0".$length_tag."s", $c);
		$new_marks{$new_name} = $mrk;

		my %genotps = %{$marks{$mrk}};
		my @genotypes = ();
		foreach my $ind (@indiv) {
	
		    push @genotypes, $genotps{$ind};
		}
		my $geno_line = lc(join("", @genotypes));

		if ($segregation{$mrk} eq 'None') {
		
		    print $ofh "$new_name\n$geno_line\n";
		}
		else {
		
		    my $seg =  $segregation{$mrk};
		    if ($seg eq '(a,b,h)') {
		    
			$seg = '(a,h,b)';
		    }

		    print $ofh "$new_name $seg\n$geno_line\n";
		}		
	    }
	}
    }

    $marks_n = $c;

    ## this format also keeps individual names
    print $ofh "\nindividual names:\n\n";
    my $name_list = join("\n", @indiv);
    print $ofh "$name_list\n\n\n";

    ## It will print also the list of equivalent loci to the new names
    foreach my $new_mrk (sort keys %new_marks) {
    
	print $ofh "; $new_mrk\t$new_marks{$new_mrk}\n"
    }   
}
elsif ($oformat eq 'csv') {

    ## CSV format (used by R/qtl) contains:
    ## column 1..X: Phenotypes, at least one.
    ## column X+1..Y: Markers
    ## row 1: Phenotypes and marker names
    ## row 2: Chromosomes numbers (empty at phenotypes columns). Use X for x 
    ##        chromosome. It will use chromosome 1 for everything
    ## row 3: distances in cM. It will omit this column
    ## row 4: individuals coded as A, B, H
    ## it will add an initial description with comments
   
    #print $ofh "## population type = $mtype\n";
    #print $ofh "## loci number = $marks_n\n";
    #print $ofh "## individual number = $indiv_n\n";

    ## Now the structure will be by row where each row is an individual

    ## create the ind hash

    my %csv_indrow = ();
    my $idx = 0;
    foreach my $ind (@indiv) {
    
	$csv_indrow{$ind} = [$idx]; ## It will add one of the fake phenotype
	$idx++;
    }

    my @header_list = ('phenotype');
    my @fake_chrom = ('');
    my @fake_dist = ('');
    my $n = 0;
    
    foreach my $chr (@chrs) {

	foreach my $mrk (@{$chr_markers{$chr}}) {	    	    

	    if (exists $selected_marks{$mrk}) {

		push @header_list, $mrk;
		push @fake_chrom, 1;
		push @fake_dist, $n;

		my %genotps = %{$marks{$mrk}};

		foreach my $ind (@indiv) {
	
		    push @{$csv_indrow{$ind}}, $genotps{$ind};
		}
		$n++;
	    }	    
	}
    }

    $marks_n = $n;

    my $header_line = join(",", @header_list);
    my $chromo_line = join(",", @fake_chrom);
    my $distan_line = join(",", @fake_dist);
    print $ofh "\n$header_line\n$chromo_line\n$distan_line\n";

    foreach my $ind (@indiv) {
    
	my $genot_line = join(",", @{$csv_indrow{$ind}});
	print $ofh "$genot_line\n";
    }
}

print STDERR "\tProduced outfile $opt_o in $oformat format\n";
print STDERR "\twith $marks_n makers and $indiv_n individuals";

$date = `date`;
chomp($date);
print STDERR "\n\n############################################################";
print STDERR "\n## Hapmap2Mapmaker Ends ($date)   ##\n";
print STDERR "############################################################\n\n";
exit;


=head2 help

  Usage: help()
  Desc: print help of this script
  Ret: none
  Args: none
  Side_Effects: exit of the script
  Example: if (!@ARGV) {
               help();
           }

=cut

sub help {
  print STDERR <<EOF;
  $0:

    Description:
      
       This script trasforms a hapmap file into a Mapmaker format

       Hapmap format is a tabular format file with the following columns:
        C1:   rs#
        C2:   alleles
        C3:   chrom
        C4:   pos
        C5:   strand
        C6:   assembly
        C7:   center
        C8:   protLSID
        C9:   assyLSID	
        C10:  panelLSID	
        C11:  QCcode	
        C12+: Genotypes

       Mapmaker format with two header lines:
        line1: "data type XXXX"
               where XXXX can be "f2 intercross", "f2 backcross", "f3 self", 
               "ri self" or "ri sib" (remember that Antmap do not use: "ri sib" 
               but it can use "dh").
        line2: XXX YYY ZZZ Additional_AAAA
               where XXX is the number of the progeny (C12+ hapmap excluding 
               progenitors and -e accessions).
               where YYY is the number of genetic loci
               where ZZZ number of quantitative traits
               where Additional_AAAA is aditional information such as the coding
               scheme (keys), for example: "symbols 1=A 2=B 3=H 0=-")
  
       After these two lines, the raw input file contains one line per locus
       where it starts with "*" plus the locus name, space (tab...) and the 
       genotypes, for example "*L1 ABABBBHH" or "*L1 A B A B B B H H". Locus 
       names are limited to alphanumeric characters + underscores "_" or 
       periods "." and must start with an aplhanumeric character.

       Comments can be inserted as "#". 
         
       Example hapmap:
     C1     C2   C3    C4   C5  C6  C7  C8  C9  C10  C11  S1  S2  S3  S4  S5  S6
     MRK01  A/T  Chr5  100  +   NA  NA  NA  NA  NA   NA   AA  TT  AA  AT  AT  AA
     MRK02  C/T  Chr5  200  +   NA  NA  NA  NA  NA   NA   CC  TT  CT  TT  CC  CC
     MRK03  C/G  Chr5  300  +   NA  NA  NA  NA  NA   NA   CC  GG  CG  CG  GG  CG

       Using Hapmap2Mapmaker -a S1 -b S2 -e S6 -k aa=1;bb=2;ab=3;ac=4;bc=5;
       cc=6;-=0 will produce: 

       Example mapmaker:
       data type f2 intercross
       3 3 0 symbols 1=A 2=B 3=H 4=C 5=D 0=-
       *MRK01 1 3 3
       *MRK02 3 2 1
       *MRK03 3 3 1

       If no key is used:

       Example mapmaker:
       data type f2 intercross
       3 3 0
       *MRK01 A H H
       *MRK02 H B A
       *MRK03 H H A
  
       Note: cc will be ignored because it is not one of the f2 defined marker
       types

       If more than one progenitor is used (for example -a S1,S6 it will try 
       to find  a consensus, if do not it will ignore that marker printing a 
       comment).
 
       Example mapmaker:
       data type f2 intercross
       3 3 0
       *MRK01 A H H
       *MRK02 H B A
       ## MRK03 has different genotypes for progenitor a (S1,S6) CC,CG

       Biallelic (-B) option filter the non-biallelic SNPs (recommended).
       

    Usage:

       Hapmap2Mapmaker [-h]  -i <hapmap_inputfile> -o <outputfile>
                       -a <donor_a> -b <donor_b> -t <data_type>
                       [-k <keys>] [-f <output_format>]
                       [-p <chisqr_pvalue>] [-s <segregation>]
                       [-e <samples_to_exclude>] [-d <distance_snps>] [-B][-H]

    Example:
   
       Hapmap2Mapmaker -i Laupala_HC1_Filter1_SNP.set_1.hmp.txt 
                       -o Laupala_HC1_Filter1_SNP.AHB121_markers_p001.csv 
                       -f csv 
                       -a HC1_D_Laeuk 
                       -b HC1_S_Lacer 
                       -e Reference 
                       -s '(a,h,b)' 
                       -p 0.001
 
    Flags:

      -i <hapmap_inputfile>     hapmap input file (mandatory)
      -o <outputfile>           output filename (mandatory)
      -f <output_format>        outout format: mapmaker (default) or jointmap4
      -a <donor_a>              donor a name(s)(separated by commas) (mandatory)
      -b <donor_b>              donor b name(s)(separated by commas) (mandatory)
      -t <data_type>            data type for mapmaker (ex. f2) (f2 by default)
      -k <keys>                 keys to code SNPs (aa=1;bb=2;ab=3...) 
      -e <samples_to_exclude>   list of samples to exclude (sep. by comma)
      -s <filter_segregation>   filter by expected segregation (optional)
      -p <chisqr_pvalue>        chi square p-value for segregation test (0.01)
      -B <biallelic_filter>     filter out the non biallelic genotypes.
      -d <distance_snps>        filter snps closer than this distance
      -V <be_verbose>           be verbose and print the parsing status.
      -h <help>                 print the help


EOF
exit (1);
}

=head2 print_header

  Usage: print_head("Message");

  Desc: print a section head

  Ret: None

  Args: Message to print in the header

  Side_Effects: None

  Example: print_head("Step1: This is a test");

=cut

sub print_header {
    my $message = shift;

    my $date = `date`;
    chomp($date);

    print STDERR "\n";
    print STDERR "============================================================";
    print STDERR "\n $message ($date)\n";
    print STDERR "============================================================";
    print STDERR "\n\n";
}

=head2 parse_hapmap

  Usage: my ($mloc_href, $mgen_href) = parse_hapmap($input);

  Desc: Parse a hapmap file and returns two hashrefs.

  Ret: $mloc_href, a hash ref. with key=$chrom and value={$id => $pos }; 
       $mgen_href, a hash ref. with key=$genot and value={$id => \@genotypes };
       $mref_href, a hash ref. with key=$id and value=$ref_allele 

  Args: $input, a filename
        $refname, a reference name

  Side_Effects: Die if something is wrong.
                It takes the refname from $opt_r

  Example: my ($mloc_href, $mgen_href) = parse_hapmap($input);

=cut

sub parse_hapmap {
    my $in = shift ||
	die("ERROR: No inputfile was supplied to parse_hapmap function.\n");
    my $a_donor_href = shift ||
	die("ERROR: No A donor was supplied to parse_hapmap function.\n");
    my $b_donor_href = shift ||
	die("ERROR: No B donor was supplied to parse_hapmap function.\n");
    my $excl_href = shift;

    my %excl = ();
    if ($excl_href && ref($excl_href) eq 'HASH') {
    
	%excl = %{$excl_href};
    }
    

    ## Define the variables

    my %a_donor = %{$a_donor_href};
    my %b_donor = %{$b_donor_href};

    my %abh_marks = ();
    my %pos_marks = ();

    ## First open the file

    open my $ifh, '<', $in;

    my ($H, $h) = (0,0);
    if ($opt_V) {
    
	$H = `cut -f1 $in | wc -l`;
	chomp($H);
    }

    my %manfields = (
	'rs#'       => 1,	
	'alleles'   => 2,	
	'chrom'	    => 3,
	'pos'	    => 4,
	'strand'    => 5,	
	'assembly'  => 6,	
	'center'    => 7,	
	'protLSID'  => 8,	
	'assyLSID'  => 9,	
	'panelLSID' => 10,	
	'QCcode'    => 11
	);
    my $mancnt = scalar(keys %manfields);
   
    my @headers = ();
    
    my @indiv = ();

    while(<$ifh>) {
	
	chomp($_);
	$h++;
    
	
	if ($_ =~ m/^rs#/) {
	
	    my $f = 0;
	    foreach my $head (split(/\t/, $_)) {
	    
		$f++;
		if ($f > 0 && $f < 12) {
		
		    unless (exists $manfields{$head}) {
		    
			my @mfields = sort {$manfields{$a} <=> $manfields{$b}} 
			keys %manfields;
			my $mfline = join(",", @mfields);
			die("ERROR: wrong header field $head isnt ($mfline)\n");
		    }
		}
		else {

		    push @indiv, $head;
		}
	    }

	}
	else {
	
	    my ($mkid, $alle, $chro, $posi, $stra, $asse, $cent, $prot, 
		$assy, $pane, $qcco, @geno) = split(/\t/, $_);		    

	    ## Definition of the hash to store the formatted genotypes

	    my %abh_geno = ();

	    ## Now it will get the genotypes per individual
	    
	    my %genotypes = ();

	    my $a = 0;
	    foreach my $ind (@indiv) {
	    
      		$genotypes{$ind} = $geno[$a];		
		$a++;
	    }

	    ## Identify the donor genotypes and count them

	    my %a_donor_gn = ();
	    foreach my $a_donor_ind (keys %a_donor) {
	    
		if (exists $a_donor_gn{$genotypes{$a_donor_ind}}) {
		
		    $a_donor_gn{$genotypes{$a_donor_ind}}++;
		}
		else {
		
		    $a_donor_gn{$genotypes{$a_donor_ind}} = 1;
		}
	    }

	    my @a_donor_gntypes = keys(%a_donor_gn); 
	    my $a_donor_gn_c = scalar(@a_donor_gntypes);

	    my %b_donor_gn = ();
	    foreach my $b_donor_ind (keys %b_donor) {
	    
		if (exists $b_donor_gn{$genotypes{$b_donor_ind}}) {
		
		    $b_donor_gn{$genotypes{$b_donor_ind}}++;
		}
		else {
		
		    $b_donor_gn{$genotypes{$b_donor_ind}} = 1;
		}
	    }

	    my @b_donor_gntypes = keys(%b_donor_gn); 
	    my $b_donor_gn_c = scalar(@b_donor_gntypes);

	    ## Check if the progenitors meet all the conditions
	    ## 1) All the A donors are the same (and same for B donors)
	    ## 2) A donor is different from B donor
	    ## 3) A and B donors are homozygous

	    my $optimal_donors = 0;

	    ## Check if they are the same
	    
	    if ($a_donor_gn_c == 1 && $b_donor_gn_c == 1) {
		
		## Check if the A_DONOR != B_DONOR

		if ($a_donor_gntypes[0] ne $b_donor_gntypes[0]) {
		
		    ## Check if they are homozygous 
		    
		    if ($opt_H) {

			if (is_homozygous($a_donor_gntypes[0])) {
		    
			    if (is_homozygous($b_donor_gntypes[0])) {
		    
				$optimal_donors = 1;
			    }		    
			}
		    }
		    else {
		    
			$optimal_donors = 1;
		    }
		}
	    }

	    if ($optimal_donors == 1) {
	    
		## Now it will check if each of the individuals is
		## A, B or H

		foreach my $ind (keys %genotypes) {

		    ## Check that the individual is not excluded

		    unless (exists $excl{$ind}) {
		
			unless (exists $a_donor{$ind}) {
		    
			    unless (exists $b_donor{$ind}) {
			
				my $gtype = '-';

				my @a_donor_n = split(//, $a_donor_gntypes[0]);
				my @b_donor_n = split(//, $b_donor_gntypes[0]);

				my @het = sort($a_donor_n[0], $b_donor_n[0]);
				my $het = join("", @het);

				if ($genotypes{$ind} eq $a_donor_gntypes[0]) {
			    
				    $gtype = 'A';
				}
				elsif ($genotypes{$ind} eq $b_donor_gntypes[0]){
			    
				    $gtype = 'B';
				}
				elsif ($genotypes{$ind} eq $het) {
				    
				    $gtype = 'H';
				}
				else {
				    
				    $gtype = 'X';
				}
			    
				$abh_geno{$ind} = $gtype;
			    }
			}
		    }
		}

		## If it meet the optical donor conditions, it will add the
		## marker to the selection.

		$abh_marks{$mkid} = \%abh_geno;

		## Add the position mark

		if (exists $pos_marks{$chro}) {
	    
		    $pos_marks{$chro}->{$mkid} = $posi;
		}
		else {
		    
		    $pos_marks{$chro} = {$mkid => $posi};
		}
	    }	    	    
	}
	
	if ($opt_V) {
	
	    print STDERR "\tParsing line: $h of $H                   \r";
	}	    
    }

    if ($opt_V) {
	
	print STDERR "\n\n";
    }
    

    return (\%abh_marks, \%pos_marks);
}

=head2 is_homozygous

  Usage: if (is_homozygous($snps)) {}

  Desc: Check if a snp is homozygous (if a string has more than one character)

  Ret: 0 or 1

  Args: $snps, a string

  Side_Effects: None

  Example: if (is_homozygous($snps)) {}

=cut

sub is_homozygous {
    my $snps = shift ||
	die("ERROR: No snps variable was supplied to is_homozygous().\n");

    ## It will check how many different nt has. If nt=1 is homozygous

    my @snps = split(//, $snps);
    my %nts = ();
    foreach my $nt (@snps) {
	
	$nts{$nt} = 1;
    }

    if (scalar(keys %nts) == 1) {
    
	return 1;
    }
    else {
    
	return 0;
    }
}

=head2 count_genotypes

  Usage: my %geno_count = count_genotypes($hashref)

  Desc: Count genotypes (values) and return a hash (key=genotypes; values=count)

  Ret: a hash

  Args: $hashref, a hash with key=anything (individuals), value=genotype

  Side_Effects: None

  Example: my %geno_count = count_genotypes($hashref)

=cut

sub count_genotypes {
    my $geno_href = shift ||
	die("ERROR: No genotypes hashref. was supplied to count_genotypes()\n");

    if (ref($geno_href) ne 'HASH') {
    
	die("ERROR: Variable supplied to count_genotypes is not hashref.\n");
    }

    my %geno = %{$geno_href};

    my %gcount = ();
    foreach my $ind (sort keys %geno) {
    
	my $gnt = $geno{$ind};
	if (exists $gcount{$gnt}) {
	
	    $gcount{$gnt}++;
	}
	else {
	
	    $gcount{$gnt} = 1;
	}
    }
    return %gcount;
}

=head2 sort_markers

  Usage: my @markers = sort_markers(\%marks, $distance);

  Desc: Sort markers and filter by distance

  Ret: An array with arrayref with markers IDs

  Args: \%marks, a hashref with key=chromosome, value=hashref with id, position

  Side_Effects: None

  Example: my @markers = sort_markers(\%marks, $distance);

=cut

sub sort_markers {
    my $mrks_href = shift ||
	die("ERROR: No marks_href variable was supplied to sort_markers()\n");
    my $dist = shift;

    if (ref($mrks_href) ne 'HASH') {
    
	die("ERROR: $mrks_href supplied to sort_markers() isnt hashref.\n");
    }

    my %mloc = %{$mrks_href};
    my %mrks = ();

    my $mrks_count = 0;

    foreach my $chr (sort keys %mloc) {

	my @chr_mrks = ();

	my %mrks_c = %{$mloc{$chr}};

	my $n = 0;

	foreach my $mrk_id (sort { $mrks_c{$a} <=> $mrks_c{$b} } keys %mrks_c) {
    		    
	    if ($dist) {
		
		if ($n == 0) {

		    push(@chr_mrks, $mrk_id);
		    $mrks_count++;
		}
		else {
		    
		    my $diff = $mrks_c{$mrk_id} - $mrks_c{$chr_mrks[-1]};
		    if ($diff > $dist) {
			
			push(@chr_mrks, $mrk_id);
			$mrks_count++;
		    }
		}
	    }
	    else {
	
		push(@chr_mrks, $mrk_id);
		$mrks_count++;
	    }
	    
	    $n++;
	}

	$mrks{$chr} = \@chr_mrks;
    }

    print STDERR "\t$mrks_count markers have been selected\n";

    return %mrks;
}

=head2 callsingle

  Usage: my $single = callsingle(\@genotypes);

  Desc: Reduce the genotypes to non-redundant call, for example:
        AA => A, AT => AT, AACC => AC, ACCT => ACT...

  Ret: An scalar with the SNP

  Args: \@genotypes, an arrayref with the genotypes

  Side_Effects: None

  Example:  my $single = callsingle(\@genotypes);

=cut

sub callsingle {

    my $geno_aref = shift ||
	die("ERROR: No genotypes arrayref variable was supplied to callsingle");

    if (ref($geno_aref) ne 'ARRAY') {
    
	die("ERROR: $geno_aref supplied to callsingle() isnt arrayref.\n");
    }

    my %dif = ();
    foreach my $allele (@{$geno_aref}) {
	
	$dif{$allele} = 1;
    }

    my $singeno = join("", sort(keys(%dif)));
    return $singeno;
}
